name: medical-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.10.0
  - scikit-learn>=1.1.0
  - nltk>=3.7
  - jupyter
  - jupyterlab
  - notebook
  - wordcloud>=1.8.0
  - ipykernel
  - ipywidgets
  - pip
  - pip:
    - streamlit>=1.28.0
    - streamlit-plotly-events>=0.0.6
    - streamlit-aggrid>=0.3.0